### PR TITLE
Use Scratch for Bathymetry

### PR DESCRIPTION
**Pull request by vchuravy**
The current directory might not be writeable and this way multiple copies of the code can share the same data.

It might make sense to use something like DataDeps/Artifacts in the long run.

### CODE REVIEW

**Comment by vchuravy** [comment]
Probably also need to do something similar for `RYF.*`

**Comment by glwagner** [comment]
cc @simone-silvestri

**Comment by simone-silvestri** [comment]
Looks good! should we include a scratch for the JRA55-downloaded files in this PR?

**Comment by glwagner** [comment]
> Looks good! should we include a scratch for the JRA55-downloaded files in this PR?

yes

**Comment by glwagner** [comment]
@simone-silvestri please review this

**Review by simone-silvestri — APPROVED** [review]

**Pull request merged**
