### PR TITLE
Speed up near global example

### PR DESCRIPTION
**Pull request by simone-silvestri**

### CODE REVIEW

**Review by glwagner — APPROVED** [review]
Let's consider making this default

**Comment by navidcy** [comment]
We could merge this PR since it's done it's purpose and look into the NaNs in a new PR?

**Comment by glwagner** [comment]
We have to find the NaNs ASAP but unfortunately we are a little tied up this week

**Comment by simone-silvestri** [comment]
https://github.com/CliMA/Oceananigans.jl/pull/3940 was causing the crashing. I ran it on main and it is not crashing anymore. I will bump the minor version in oceananigans and we can get the example back and running.

**Comment by glwagner** [comment]
great

**Pull request merged**
