### PR TITLE
Remove literated examples; a try

### PR DESCRIPTION
**Pull request by navidcy**
I'd like to see the docs built once and then add literate examples one by one.

### CODE REVIEW

**Review by glwagner — APPROVED** [review]

**Comment by navidcy** [comment]
Note: I changed the README style a bit to consist _only_ markdown. This way we can use the README as the Docs landing page and we only have to maintain one thing.

**Comment by glwagner** [comment]
> Note: I changed the README style a bit to consist _only_ markdown. This way we can use the README as the Docs landing page and we only have to maintain one thing.

Ultimately I think we will want different pages but we can start with that. I think we will want to devote quite a bit to these docs eventually, when it becomes the main source of info about realistic ocean and sea ice simulations. So it will be worth it to tailor the README and docs.

**Comment by navidcy** [comment]
Yes, agreed that this is just a start.
Better having the readme there than nothing. We can alter later!

**Comment by glwagner** [comment]
Probably you're right. But a counter argument is that it gives us the excuse to put off writing legitimate docs! :-D I kinda think it looks bad to copy and paste that though. I will try to update it soon.

**Comment by navidcy** [comment]
Oh feel free to remove then, no problem!

**Comment by glwagner** [comment]
I'll write something. I don't see it up yet though.

**Comment by navidcy** [comment]
Oh... it'll take few hours (if the deploy succeeds!)

**Comment by navidcy** [comment]
https://buildkite.com/clima/climaocean-examples/builds/879#01931931-405f-4220-8726-e0aacde7f428

**Pull request merged**
