### PR TITLE
Add the near-global example in the Docs

### PR DESCRIPTION
**Pull request by navidcy**

### CODE REVIEW

**Comment by simone-silvestri** [comment]
nice, shall we also add the other ones since the docs are built now?

**Comment by navidcy** [comment]
I wanted to add them one by one. I think the surface fluxes and the Mediterranean were broken (last week that I was trying them out).

**Comment by simone-silvestri** [comment]
I think the surface flux test case is working. The Mediterranean test case was not ready yet.

**Comment by navidcy** [comment]
OK, I'll add them all but the Mediterranean in a next PR

**Comment by navidcy** [comment]
Actually I just run the examples locally (except the Mediterranean) and they all run until the end no errors.

**Pull request merged**
