### PR TITLE
Put nice formatting in the README + new docs landing page

### PR DESCRIPTION
**Pull request by glwagner**
I can't remember if this was never added in the first place or got eliminated.

### CODE REVIEW

**Comment by navidcy** [comment]
I converted the readme in all markdown so it can be the landing page in the docs

**Comment by glwagner** [comment]
Ah ok but I think the README is the most read thing so it has higher priority right?

**Comment by navidcy** [comment]
This PR will break the docs. Happy with it though if you like the style better. 

Perhaps let’s just revert the landing docs page to an empty placeholder one like before? Empty is better than broken.

**Comment by navidcy** [comment]
I can do it.

**Comment by glwagner** [comment]
What do we want to put on the landing page?

**Comment by glwagner** [comment]
The actual process of copy/pasting or writing code to change the landing page is probably more effort than actually just writing something simple!

**Comment by navidcy** [comment]
Yeah, I'll write 1-2 sentences and urge people to look at the examples.

**Comment by glwagner** [comment]
I wrote a few paragraphs let me know what you think.

**Comment by glwagner** [comment]
I wrote a few paragraphs let me know what you think.

**Review by navidcy — APPROVED** [review]

**Comment by glwagner** [comment]
Shouldn't the label be called "build docs"? Why say "built" in past tense?

**Comment by navidcy** [comment]
typo ;)

**Comment by glwagner** [comment]
> typo ;)

touche

**Pull request merged**
