### PR TITLE
Better plot for single-column example

### PR DESCRIPTION
**Pull request by navidcy**
Better subplot structure

### CODE REVIEW

**Review by glwagner — APPROVED** [review]
It's still broken right?

**Comment by glwagner** [comment]
ok i think we will see here https://clima.github.io/ClimaOceanDocumentation/previews/PR268

the fluxes are broken right now

**Comment by navidcy** [comment]
Changed the figure structure; I believe the original figure must have been made on a huge screen.

**Comment by navidcy** [comment]
https://github.com/user-attachments/assets/29d69e91-1a93-4c5a-88b5-b2d309274597

**Comment by glwagner** [comment]
That looks nicer for sure. Before you go too far in making it look better, it might be good to assess whether we want to add or remove any panels or information from the plot too?

**Pull request merged**
