### PR TITLE
Add a test that sets temperature and salinity to ECCOMetadata

### LINKED ISSUE #197: `near_global_ocean_simulation.jl` is broken
There's something wrong with #180. Running `near_global_ocean_simulation.jl` gives me the error

```julia
julia> include("near_global_ocean_simulation.jl")
[ Info: Regridding bathymetry from existing file /orcd/data/raffaele/001/glwagner/.julia/scratchspaces/0376089a-ecfe-4b0e-a64f-9c555d74d754/Bathymetry/ETOPO_2022_v1_60s_N90W180_surface.nc.
┌ Warning: This simulation will run forever as stop iteration = stop time = wall time limit = Inf.
└ @ Oceananigans.Simulations /orcd/data/raffaele/001/glwagner/.julia/packages/Oceananigans/ezEr7/src/Simulations/simulation.jl:55
ERROR: LoadError: NetCDF error: Opening path /orcd/data/raffaele/001/glwagner/.julia/scratchspaces/0376089a-ecfe-4b0e-a64f-9c555d74d754/ECCO/THETA.1440x720x50.19930101.nc: No such file or directory (NetCDF error code: 2)
Stacktrace:
  [1] nc_open(path::String, mode::UInt16)
    @ NCDatasets /orcd/data/raffaele/001/glwagner/.julia/packages/NCDatasets/PkTUf/src/netcdf_c.jl:275
  [2] NCDatasets.NCDataset(filename::String, mode::String; format::Symbol, share::Bool, diskless::Bool, persist::Bool, memory::Nothing, maskingvalue::Missing, attrib::Vector{Any})
    @ NCDatasets /orcd/data/raffaele/001/glwagner/.julia/packages/NCDatasets/PkTUf/src/dataset.jl:211
  [3] NCDataset (repeats 2 times)
    @ /orcd/data/raffaele/001/glwagner/.julia/packages/NCDatasets/PkTUf/src/dataset.jl:170 [inlined]
  [4] ECCO_field(metadata::ECCOMetadata{DateTimeProlepticGregorian, ClimaOcean.DataWrangling.ECCO.ECCO2Daily}; architecture::GPU, horizontal_halo::Tuple{Int64, Int64})
    @ ClimaOcean.DataWrangling.ECCO /orcd/data/raffaele/001/glwagner/ClimaOcean.jl/src/DataWrangling/ECCO/ECCO.jl:150
  [5] ECCO_field
    @ /orcd/data/raffaele/001/glwagner/ClimaOcean.jl/src/DataWrangling/ECCO/ECCO.jl:140 [inlined]
  [6] ECCO_mask(metadata::ECCOMetadata{DateTimeProlepticGregorian, ClimaOcean.DataWrangling.ECCO.ECCO2Daily}, architecture::GPU; minimum_value::Float32, maximum_value::Float32)
    @ ClimaOcean.DataWrangling.ECCO /orcd/data/raffaele/001/glwagner/ClimaOcean.jl/src/DataWrangling/ECCO/ECCO_mask.jl:12
  [7] ECCO_mask
    @ /orcd/data/raffaele/001/glwagner/ClimaOcean.jl/src/DataWrangling/ECCO/ECCO_mask.jl:8 [inlined]
  [8] set!(field::Field{…}, ECCO_metadata::ECCOMetadata{…}; kw::@Kwargs{})
    @ ClimaOcean.DataWrangling.ECCO /orcd/data/raffaele/001/glwagner/ClimaOcean.jl/src/DataWrangling/ECCO/ECCO.jl:260
  [9] set!(field::Field{…}, ECCO_metadata::ECCOMetadata{…})
    @ ClimaOcean.DataWrangling.ECCO /orcd/data/raffaele/001/glwagner/ClimaOcean.jl/src/DataWrangling/ECCO/ECCO.jl:255
 [10] apply_regionally!(::Function, ::Field{…}, ::Vararg{…}; kwargs::@Kwargs{})
    @ Oceananigans.Utils /orcd/data/raffaele/001/glwagner/.julia/packages/Oceananigans/ezEr7/src/Utils/multi_region_transformation.jl:121
 [11] apply_regionally!
    @ /orcd/data/raffaele/001/glwagner/.julia/packages/Oceananigans/ezEr7/src/Utils/multi_region_transformation.jl:118 [inlined]
 [12] macro expansion
    @ /orcd/data/raffaele/001/glwagner/.julia/packages/Oceananigans/ezEr7/src/Utils/multi_region_transformation.jl:206 [inlined]
 [13] #set!#41
    @ /orcd/data/raffaele/001/glwagner/.julia/packages/Oceananigans/ezEr7/src/Models/HydrostaticFreeSurfaceModels/set_hydrostatic_free_surface_model.jl:60 [inlined]
 [14] top-level scope
    @ /orcd/data/raffaele/001/glwagner/ClimaOcean.jl/examples/near_global_ocean_simulation.jl:97
 [15] include(fname::String)
    @ Base.MainInclude ./client.jl:489
 [16] top-level scope
    @ REPL[5]:1
in expression starting at /orcd/data/raffaele/001/glwagner/ClimaOcean.jl/examples/near_global_ocean_simulation.jl:97
Some type information was truncated. Use `show(err)` to see complete types.
```

I also found this error when trying to run a different global ocean simulation. There's something wrong with how the scratch space is created for ECCO data.

Is this tested?

@simone-silvestri

### LINKED ISSUE #199: `ECCOMetadata.path` is named incorrectly
This variable gives a directory -- not a path to the file. The whole filepath is actually constructed with `joinpath(path, filename)`. We should change the name of this property to `directory` or `dir` or something.

https://github.com/CliMA/ClimaOcean.jl/blob/d56812fa4f11985bd32ea68278325a1ac03e45b4/src/DataWrangling/ECCO/ECCO_metadata.jl#L22

### LINKED ISSUE #200: What happens when we iterate over `ECCOMetadata`?
I'm confused by these lines:

https://github.com/CliMA/ClimaOcean.jl/blob/1280a9dab180e11e6c19f8f019abab0825f1670f/src/DataWrangling/ECCO/ECCO_metadata.jl#L184

It looks like the elements of `ECCOMetadata` are also `ECCOMetadata`. It's not very intuitive to me, wouldn't a single piece of "data" be a "datum"? Why are they both called `ECCOMetadata`?

This comes up because I'm trying to fix the bug in #197 and also clean up the ECCO utilities at the same time. A key missing abstraction is something that returns a path to the data and I think that's where the bug comes up.

### PR DESCRIPTION
**Pull request by glwagner**
A bit of a paranoid test since it seems this is already tested, but it does add an element whereby the date is explicitly specified in ECCOMetadata.

Resolves #197 
Resolves #200 
Resolves #199

### CODE REVIEW

**Review by navidcy — APPROVED** [review]
lgtm

**Comment by glwagner** [comment]
@navidcy I'm trying to understand if the tests even run...

**Comment by glwagner** [comment]
There's a bug in Oceananigans that causes tests to fail. Will be fixed with 0.93.1

https://github.com/CliMA/Oceananigans.jl/pull/3871

**Comment by simone-silvestri** [comment]
I think this change also warrants having `path` and `name` in the backend (in Oceananigans). Because at the moment, with this PR, they are unused if using `ECCONetCDFBackend` leaving some ambiguity as to where the file is taken.

**Comment by glwagner** [comment]
`path` and `name` could be stored in `OnDisk`

**Comment by glwagner** [comment]
I think the reason we didn't make this change is because it doesn't gel with the user interface, which we have to consider (in addition to consider the design of low level interfaces).

For example, users provide `path` and `name` to the `FieldTimeSeries` constructor, eg `FieldTimeSeries(path, name)` when using it for post processing. This works for `OnDisk` and `InMemory` similarly even though `InMemory` doesn't have a `path` and `name`.

I'd like to see the syntax that you propose for the user interface _first_, then we can discuss changing the underlying implementation.

**Comment by glwagner** [comment]
> Because at the moment, with this PR, they are unused if using ECCONetCDFBackend leaving some ambiguity as to where the file is taken.

I don't think there is ambiguity. With `ECCONetCDFBackend`, the data comes from the ECCO file specified by the backend, without any ambiguity.

We can also build a `FieldTimeSeries` without a `path` and `name` at all (eg just a 4D dataset).

In both cases `path` and `name` should be `nothing` indicating that they are unused.

But I'd like to understand more what you mean by 'ambiguity'

**Comment by simone-silvestri** [comment]
Why should there be problems with having an interface with `FieldTimeSeries(path, name)` and the path and name in the backend? 
I think that if we are seeing that many times, `path` and `name` have to be a `nothing`, it makes sense to include them in the backend that needs them (indeed, like `OnDisk`). 
Also `InMemory` would require a path and a name if it is not fully in memory

**Comment by glwagner** [comment]
> Why should there be problems with having an interface with `FieldTimeSeries(path, name)` and the path and name in the backend? I think that if we are seeing that many times, `path` and `name` have to be a `nothing`, it makes sense to include them in the backend that needs them (indeed, like `OnDisk`). Also `InMemory` would require a path and a name if it is not fully in memory

What do you propose happens when a user writes `FieldTimeSeries(path, name, backend=OnDisk()`? Would we magically add `path` and `name` to `OnDisk`? The problem is that this is "surprising" which is undesirable.

**Pull request merged**
