### PR TITLE
Fix a bug in `MinimumTemperatureSeaIce` and limit temperature in the water column

### PR DESCRIPTION
**Pull request by simone-silvestri**
This was for sure the problem with the cooling case in #251 and I believe is also what is causing #237, 
because we cap cooling fluxes on the base of the temperature of the bottom cell.
This is almost always 0 in the arctic because it is immersed, causing cooling fluxes to always be active and reducing the temperature much below the freezing point. I am not sure about the temperature increasing too much in the tropics though.

I ll also build the examples to see if this is the problem

### CODE REVIEW

**Comment by navidcy** [comment]
Could you see if the #237 issue went away from just the preview of the docs? The colorbar is saturated so it's hard to see if T remains bounded from the short movie I think..

**Comment by glwagner** [comment]
I think this is superceded by #255

**Comment by navidcy** [comment]
Great.

Btw, I see this in the docs preview

```Julia
[ Info: Iter: 10320, time: 15 days, Δt: 10 minutes, max|u|: (1.97e+00, 1.93e+00, 1.62e-02) m s⁻¹, extrema(T): (41.52, -2.38) ᵒC, wall time: 9.169 minutes
[ Info: Iter: 11040, time: 20 days, Δt: 10 minutes, max|u|: (1.77e+00, 1.84e+00, 1.84e-02) m s⁻¹, extrema(T): (43.43, -2.47) ᵒC, wall time: 9.139 minutes
[ Info: Iter: 11760, time: 25 days, Δt: 10 minutes, max|u|: (1.66e+00, 2.29e+00, 1.78e-02) m s⁻¹, extrema(T): (45.50, -2.29) ᵒC, wall time: 9.142 minutes
[ Info: Iter: 12480, time: 30 days, Δt: 10 minutes, max|u|: (2.16e+00, 2.18e+00, 2.18e-02) m s⁻¹, extrema(T): (46.91, -2.27) ᵒC, wall time: 9.138 minutes
[ Info: Iter: 13200, time: 35 days, Δt: 10 minutes, max|u|: (2.29e+00, 2.27e+00, 3.02e-02) m s⁻¹, extrema(T): (47.06, -4.32) ᵒC, wall time: 9.138 minutes
[ Info: Iter: 13920, time: 40 days, Δt: 10 minutes, max|u|: (1.99e+00, 2.27e+00, 2.81e-02) m s⁻¹, extrema(T): (47.64, -2.91) ᵒC, wall time: 9.132 minutes
[ Info: Iter: 14640, time: 45 days, Δt: 10 minutes, max|u|: (2.06e+00, 2.05e+00, 2.56e-02) m s⁻¹, extrema(T): (48.15, -2.61) ᵒC, wall time: 9.145 minutes
[ Info: Iter: 15360, time: 50 days, Δt: 10 minutes, max|u|: (2.31e+00, 2.39e+00, 2.73e-02) m s⁻¹, extrema(T): (47.23, -2.39) ᵒC, wall time: 9.146 minutes
[ Info: Iter: 16080, time: 55 days, Δt: 10 minutes, max|u|: (2.90e+00, 3.15e+00, 2.75e-02) m s⁻¹, extrema(T): (48.57, -2.80) ᵒC, wall time: 9.132 minutes
```

which suggests great improvement from temperatures -35C!  But I thought ti should go down to -1.8C, no?

**Comment by navidcy** [comment]
> I think this is superceded by #255

Close this then?

**Pull request closed without merging**
