### PR TITLE
Add a download test on windows

### LINKED ISSUE #179: Difficuty accessing ECCO file
On trying the example generate_surface_fluxes.jl at the line

mask=ecco_mask()
I get the error (in this minimal example)
run(`wget --http-user=kevin_broughan --http-passwd=Nasa44earth-data 'https://ecco.jpl.nasa.gov/drive/files/ECCO2/cube92_latlon_quart_90S90N/daily/THETA\THETA.1440x720x50.19930101.nc'`)
ERROR: IOError: could not spawn `wget --http-user=kevin_broughan --http-passwd=Nasa44earth-data 'https://ecco.jpl.nasa.gov/drive/files/ECCO2/cube92_latlon_quart_90S90N/daily/THETA\THETA.1440x720x50.19930101.nc'`: no such file or directory (ENOENT)
However, when I login to Nasa earth data and navigate to the file the file its in place at 74.5Mb.  

I tried running Julia as su with no change in other problematic examples.

Thanks for looking at this -- Kevin

### PR DESCRIPTION
**Pull request by simone-silvestri**
should close #179. I have to find a way to use Downloads.jl with username and password. Probably HTTP.jl works better?

### CODE REVIEW

**Comment by simone-silvestri** [comment]
There is probably a way by using a file that stores login info https://discourse.julialang.org/t/download-a-url-with-a-password/93669/10

**Comment by glwagner** [comment]
Hmm true, that is interesting. The downside of the `.netrc` file is that it is less flexible than environment variables. 

If `.netrc` is the only method that works, we can start with that. We might be able to make things easier in the future if we need to (eg auto-writing `.netrc` files or something).

**Comment by glwagner** [comment]
Description of `.netrc` files: https://www.gnu.org/software/inetutils/manual/html_node/The-_002enetrc-file.html

**Comment by glwagner** [comment]
Thinking about it more I feel the `.netrc` file makes a lot of sense. It's also nice to be able to copy a dedicated file easily between machines (imagine a file with tons of users/pwds) rather than copy/pasting bits in a `.bashrc` file or something. So `.netrc` seems better.

We can write a utility that writes to `.netrc` files if we need some programmatic convenience at some point.

**Pull request closed without merging**
