### PR TITLE
Initial conditions and Fluxes

### PR DESCRIPTION
**Pull request by simone-silvestri**
Tools to produce a realistic initial condition and fluxes

(To improve)

### CODE REVIEW

**Comment by glwagner** [comment]
Maybe start over without all the binary files?

**Comment by glwagner** [comment]
Just a reminder that this branch needs to be deleted (because it carries a lot of heavy binary files)

**Comment by simone-silvestri** [comment]
Binaries are removed

**Comment by glwagner** [comment]
I believe they are still in history, so you need to delete this branch and open a new PR

**Comment by navidcy** [comment]
Were these .bin ever lived on main? If so we need to perform deeper cleaning. :)

**Comment by simone-silvestri** [comment]
nono just on this branch

**Pull request closed without merging**
