### PR TITLE
Generalize "runoff" to any "auxiliary" freshwater flux for clarity

### PR DESCRIPTION
**Pull request by glwagner**
This PR attempts to clarify how the code reads by exchanging the term "runoff" for "auxiliary_freshwater_flux". The point is that what we call "runoff" is not really specific to runoff at all (and besides, it also applies to icebergs which is not "runoff"). 

Rather the fluxes that are now called "runoff" actually allows users to implement prescribed atmospheres that have two kinds of freshwater flux --- one on the "main" grid common to other atmospheric variables, and a second one on a "different" grid (also with different times).

### CODE REVIEW

**Review by simone-silvestri — APPROVED** [review]
adding a test would be nice

**Comment by glwagner** [comment]
We can but note that this PR does not add functionality

**Comment by glwagner** [comment]
@simone-silvestri in painting seems to take a long time:

https://buildkite.com/clima/climaocean-ci/builds/1237#01917130-a246-49fd-8850-ac2df60453f1/202-597

any idea why? Can we use a smaller test for this?

**Comment by simone-silvestri** [comment]
We can also inpaint the field partially. 
There is this keyword argument `maxiter` for `inpaint_mask!` that we can propagate from outside. This should make the tests lighter.

**Comment by glwagner** [comment]
> We can also inpaint the field partially. There is this keyword argument `maxiter` for `inpaint_mask!` that we can propagate from outside. This should make the tests lighter.

Why don't we inpaint something that is, say, 10x10x10?

**Pull request merged**
