### PR TITLE
Add example that plots JRA55 data

### PR DESCRIPTION
**Pull request by glwagner**

### CODE REVIEW

**Comment by navidcy** [comment]
A start on rotating axes while animating

```Julia
using ClimaOcean
using GLMakie
using Oceananigans
using Oceananigans.Units
using Printf

time_indices = 1:300
rht = ClimaOcean.JRA55.jra55_field_time_series(:relative_humidity; time_indices)

function lonlat2xyz(lons::AbstractVector, lats::AbstractVector)
    x = [cosd(lat) * cosd(lon) for lon in lons, lat in lats]
    y = [cosd(lat) * sind(lon) for lon in lons, lat in lats]
    z = [sind(lat)             for lon in lons, lat in lats]
    return (x, y, z)
end

function lonlat2xyz(lons::AbstractMatrix, lats::AbstractMatrix)
    x = @. cosd(lats) * cosd(lons)
    y = @. cosd(lats) * sind(lons)
    z = @. sind(lats)
    return (x, y, z)
end

λ, φ, z = nodes(rht)
x, y, z = lonlat2xyz(λ, φ)

times = rht.times
Nt = length(times)
n = Observable(1)

rhn = @lift interior(rht[$n], :, :, 1)

scene = Scene()
cam3d!(scene)
surface!(scene, x, y, z, color=rhn, colormap=:grays, colorrange=(0, 100))
scale!(scene, 1.5, 1.5, 1.5)
rotate!(scene, Vec3f(0, 0, 1), π/3)
scene

record(scene, "test_rotate_axis.mp4", 1:Nt, framerate=12) do nn
    n[] = nn
    rotate!(scene, Vec3f(0, 0, 1), nn * 2π/Nt)
end
```

**Comment by navidcy** [comment]
Uploading test_rotate_axis.mp4…

**Comment by navidcy** [comment]
This is useful, but I didn't use `ax3.azimuth` which may be making things even more easier.

```Julia
scene = Scene(resolution=(1400, 700))
subsw = Scene(scene, px_area=Rect(0, 0, 700, 700), clear=true)
subrh = Scene(scene, px_area=Rect(700, 0, 700, 700), clear=true)

cam3d!(subsw)
swsurf = surface!(subsw, x, y, z, color=Qswn, colorrange=(0, 1200))
scale!(subsw, 1.5, 1.5, 1.5)

cam3d!(subrh)
surface!(subrh, x, y, z, color=rhn, colormap=:grays, colorrange=(0, 100))
scale!(subrh, 1.5, 1.5, 1.5)

scene

record(scene, "test_rotate_axis.mp4", 1:Nt, framerate=16) do nn
    @info nn/Nt
    n[] = nn
    cam3d!(subsw)
    rotate!(subsw, Vec3f(0, 0, 1), nn * π/8 / Nt)
    cam3d!(subrh)
    rotate!(subrh, Vec3f(0, 0, 1), nn * π/8 / Nt)
end
```

**Comment by navidcy** [comment]
https://github.com/CliMA/ClimaOcean.jl/assets/7112768/da7f5d7a-12a7-4533-af83-fc9e91fd2f2f

**Review by navidcy — APPROVED** [review]

**Comment by navidcy** [comment]
https://github.com/CliMA/ClimaOcean.jl/assets/7112768/7ca49192-2eb4-4c32-8268-ef7f510504da

**Comment by glwagner** [comment]
that is awesome!

**Pull request merged**
